apiVersion: v1
kind: Service
metadata:
  name: journal-api
  labels:
    app: journal-api
spec:
  type: LoadBalancer
  selector:
    app: journal-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
